name: Denomantic Release

description: Semantic release for Deno project

inputs:
  token:
    description: GitHub access token authorized to run workflows
    required: true
    default: ${{ github.token }}

  repository:
    description: target repository
    required: true
    default: ${{ github.repository }}

  denopendabot:
    description: running mode of denopendabot ('action', 'app', or 'disabled')
    required: true
    default: action

  options:
    description: options passed through to the CLI
    required: false

runs:
  using: composite
  steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.28.1 # @denopendabot denoland/deno

    - id: run
      run: >
        deno run -q --allow-env --allow-net --allow-write
        https://deno.land/x/denomantic_release@0.8.0/cli.ts
        ${{ inputs.repository }}
        --token ${{ inputs.token }}
        ${{ inputs.options }}
      shell: bash

    - uses: hasundue/denopendabot@0.12.0 # @denopendabot hasundue/denopendabot
      if: ${{ steps.run.outputs.needs_update && inputs.denopendabot != 'disabled' }}
      with:
        mode: ${{ inputs.denopendabot }}
        release: ${{ steps.run.outputs.version }}
        auto-merge: any

outputs:
  version:
    description: version of the release to be created
    value: ${{ steps.run.outputs.version }}

  needs_update:
    description: true if version numbers should be updated before release
    value: ${{ steps.run.outputs.needs_update }}

  released:
    description: release_id if created
    value: ${{ steps.run.outputs.released }}
