name: Denopendabot

on:
  workflow_dispatch:
  schedule:
    - cron: "23 23 * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: hasundue/denopendabot@0.5.0
        with:
          token: ${{ secrets.GH_TOKEN }}
