name: Denopendabot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          event-type: denopendabot-run
