name: Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    name: Release

    if: ${{ github.repository_owner == 'hasundue' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Run denomantic-release
        uses: ./
        with:
          script: ./cli.ts
          denopendabot: app
