name: Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    name: Release

    if: ${{ github.repository_owner == 'hasundue' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.2 # @denopendabot denoland/deno

      - name: Run denomantic-release
        id: run
        run: >
          deno run -q --allow-env --allow-net --allow-write ./main.ts
          ${{ github.repository }}

      - name: Update version number by Denopendabot
        if: ${{ failure() }}
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: denopendabot-run
          client-payload: '{ "release": "${{ steps.run.outputs.VERSION }}" }'
