name: Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    name: Release

    if: ${{ github.repository_owner == 'hasundue' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.2 # @denopendabot denoland/deno

      - name: Run denomantic-release
        id: run
        run: >
          deno run -q --allow-env --allow-net --allow-write ./main.ts
          ${{ github.repository }}

      - name: Run denopendabot to update version numbers
        if: ${{ !steps.run.outputs.release }}
        uses: hasundue/denopendabot@0.7.0 # @denopendabot hasundue/denopendabot
        with:
          user-token: ${{ secrets.GH_TOKEN }}
          options: --release ${{ steps.run.outputs.version }}
