name: Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    name: Release

    if: ${{ github.repository_owner == 'hasundue' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.27.1 # @denopendabot denoland/deno

      - name: Run denomantic-release
        id: run
        run: >
          deno run -q --allow-env --allow-net --allow-write ./cli.ts
          ${{ github.repository }}
          --token ${{ secrets.GITHUB_TOKEN }}

      - name: Run Denopendabot to update version numbers
        if: ${{ steps.run.outputs.needs_update }}
        uses: hasundue/denopendabot@0.12.0 # @denopendabot hasundue/denopendabot
        with:
          mode: app
          release: ${{ steps.run.outputs.version }}
