name: Release

on:
  push:
    branches:
      - main

env:
  account_id: ${{ secrets.ACCOUNT_ID }}
  api_token: ${{ secrets.API_TOKEN }}

jobs:
  release:
    name: Release
    if: ${{ github.repository_owner == 'hasundue' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install ghlog
        run: deno install -A https://pax.deno.dev/hasundue/ghlog/ghlog.ts 

      - name: Generate Release Notes
        run: ghlog ${{ github.repository }} -s | xargs -I {tag} echo "NEW_TAG={tag}" >> $GITHUB_ENV

      - name: Create a release
        id: release
        if: ${{ env.NEW_TAG != 'UNRELEASED' }}
        uses: ncipollo/release-action@v1
        with:
          tag: '${{ env.NEW_TAG }}'
          name: '${{ env.NEW_TAG }}'
          bodyFile: 'CHANGELOG.md'
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
