name: Test

on:
  pull_request:
    branches: 
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.31.3 # @denopendabot denoland/deno

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno task test -q --coverage=./coverage

      - name: Create coverage report
        run: deno coverage ./coverage --lcov > ./coverage.lcov

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.lcov
          fail_ci_if_error: true

  action:
    name: Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run action
        uses: ./
        with:
          script: ./cli.ts
          options: --dry-run --draft
