name: Denopendabot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: hasundue/denopendabot@0.5.6
        with:
          token: ${{ secrets.GH_TOKEN }}
