name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "23 23 * * *"

jobs:
  update-deps:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install udd
        run: deno install -A https://deno.land/x/udd/main.ts --name udd

      - name: Update dependencies
        run: udd mod.ts | xargs -I {result} echo "UDD_RESULT={result}" >> $GITHUB_ENV

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v4
        id: pr
        with:
          commit-message: "build(deps): update dependencies"
          title: "build(deps): update dependencies"
          body: |-
            Dependencies updated by [udd](https://github.com/hayd/deno-udd).

            ```
            ${{ env.UDD_RESULT }}
            ```
          branch: udd-deps
          author: GitHub <noreply@github.com>
          delete-branch: true

  update-deps-dev:
    name: Update dev dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install udd
        run: deno install -A https://deno.land/x/udd/main.ts --name udd

      - name: Update dependencies
        run: udd test.ts | xargs -I {result} echo "UDD_RESULT={result}" >> $GITHUB_ENV

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v4
        id: pr
        with:
          commit-message: "build(deps-dev): update dependencies"
          title: "build(deps-dev): update dependencies"
          body: |-
            Dependencies updated by [udd](https://github.com/hayd/deno-udd).

            ```
            ${{ env.UDD_RESULT }}
            ```
          branch: udd-deps-dev
          author: GitHub <noreply@github.com>
          delete-branch: true
