name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "23 23 * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.0

      - name: Run Denopendabot
        run: >
          deno run -A https://pax.deno.dev/hasundue/denopendabot/cli.ts
          main.ts mod.ts test.ts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
